### ISSUE TITLE
Can't instantiate ABC

### ISSUE THREAD

**Issue by Yitang233** [freddyaboulton/gradio-range-slider#4]
I tried your demo but there is a `TypeError: Can't instantiate abstract class RangeSlider with abstract method example_inputs`. After digging I found the `RangeSlider` class inherits from `FormComponent`, which in turn inherits from `Component`, which ultimately inherits from `ComponentBase`. And there's `@abstractmethod def example_inputs(self) -> Any:` in `ComponentBase` which seems not implemented in your class, and that prevents compilation. Could you please check that issue?

**Comment by freddyaboulton** [comment]
What version of gradio are you using? I cannot repro on 4.31.5

**Comment by Yitang233** [comment]
I'm using 4.20.0 and forget to update lol
