### ISSUE TITLE
Update via inputs not working

### ISSUE THREAD

**Issue by henryruhs** [freddyaboulton/gradio-range-slider#8]
When using input() or .release() the updates via the inputs are not being applied when typing.

I do in fact need .change() as well to make it work.

![image](https://github.com/freddyaboulton/gradio-range-slider/assets/1835397/67661f11-6f78-47ed-b6a4-5ce9e9bc428e)

**Comment by freddyaboulton** [comment]
We can trigger the release event when the number input is unfocused. This is the same behavior as gradio core slider.

Here is a demo of change, release, and input events being triggered - 

![rangeslider_events](https://github.com/freddyaboulton/gradio-range-slider/assets/41651716/70845a6a-89a9-48d9-a505-5c9350a1029a)

You can install from here to test - 
https://gradio-builds.s3.amazonaws.com/rangeslider/issue_0008/attempt_01/gradio_rangeslider-0.0.6-py3-none-any.whl

**Comment by henryruhs** [comment]
@freddyaboulton I tested it and seems to work with release only now. Thanks
